all:
  children:
    routers:
      hosts:
        sandbox_router:
          ansible_host: "{{ lookup('env', 'ROUTER_IP') }}"
          ansible_network_os: cisco.ios.ios
          ansible_connection: network_cli
          ansible_user: "{{ lookup('env', 'ROUTER_USER') }}"
          ansible_password: "{{ lookup('env', 'ROUTER_PASS') }}"
